### ISSUE TITLE
display diff in reverse

### ISSUE THREAD

**Issue by komuw** [akshayjshah/attest#4]
If you have a program like (https://go.dev/play/p/6gWHICoz0xd):
```go
got := "hello"
want := "hell"
attest.Equal(t, got, want)
```
and you run it, you get a diff like:
```diff
    prog.go:12: got != want
        diff (+got, -want):
          string(
        - 	"hell",
        + 	"hello",
          )
```

In `attest` all the functions like `Equal` take `got` as the first argument and then `want`.  So I would expect that when it comes to displaying the diff, it would follow the same order. ie, `got` is displayed first and then `want`.  
However the diff displays the `want` first(in the example above; ` - 	"hell",`)

**Comment by akshayjshah** [comment]
Hi @komuw! Sorry for the delay, I was on vacation for a bit.

`cmp.Diff` takes its arguments in the opposite order. The printed diff in your example is correct: compared to the expected result, you're missing "hell" and have "hello" instead.

**Comment by komuw** [comment]
I was talking about the order(or sequence).
The signature of `attest.Equal` is; 
```go
attest.Equal(t, got, want)
                ^      ^
       got is first    want is second
```
and in the failure message;
```go
diff (+got, -want):
        ^      ^
 got is first  want is second
```
and in the diff;
```go
string(- "hell", + "hello", )
           ^         ^
want is first got is second
```

so in the diff, the sequence is flipped: `want comes first` 


But it is a minor thing and I'm happy to close this.

Thanks for the awesome library!
