### ISSUE TITLE
add attest.NotEqual

### ISSUE THREAD

**Issue by komuw** [akshayjshah/attest#5]
currently you have to do `attest.True(t, a!=b)` which does not work for all types. 
eg;
```go
type foo struct{ Name []string }
```
the following works;
```go
attest.Equal(t, foo{Name: []string{"a"}}, foo{Name: []string{"a"}})
```

whereas the following fails to compile(`invalid operation: foo{…} != foo{…} (struct containing []string cannot be compared)`);
```go
attest.True(t, foo{Name: []string{"a"}} != foo{Name: []string{"b"}})
```

That's why I think we need a `NotEqual` so that we can write;`
```go
attest.NotEqual(t, foo{Name: []string{"a"}}, foo{Name: []string{"b"}})
```

**Comment by akshayjshah** [comment]
Makes sense to me! I'll add this later tonight.
